name: Deploy Web (GitHub Pages)

on: [push]

jobs:
  build-and-deploy:
    name: Build and deploy apps/web to GitHub Pages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web

    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'dodieboy'
          reponame: 'TutorGuru'
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
